// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'addTaskBtn': string;

  'addTaskIcon': string;

  'cardBadge': string;

  'cardBadgeDot': string;

  'cardBadgeText': string;

  'cardFieldFull': string;

  'cardFieldHalf': string;

  'cardFields': string;

  'cardFooter': string;

  'cardHeader': string;

  'cardIn': string;

  'confirmBar': string;

  'confirmText': string;

  'dateNav': string;

  'datePill': string;

  'datePillDay': string;

  'datePillFull': string;

  'deleteRowBtn': string;

  'fadeIn': string;

  'footerActions': string;

  'footerBar': string;

  'footerExceeds': string;

  'footerTotal': string;

  'footerTotalLabel': string;

  'footerTotalNum': string;

  'heroBadges': string;

  'heroHeader': string;

  'heroLabel': string;

  'heroText': string;

  'heroUser': string;

  'homeBtn': string;

  'hoursErrMsg': string;

  'hoursError': string;

  'hoursLabel': string;

  'hoursPill': string;

  'hoursPillExceeds': string;

  'hoursPillLabel': string;

  'hoursPillNum': string;

  'hoursStepper': string;

  'hoursValue': string;

  'loadingWrap': string;

  'messages': string;

  'navArrow': string;

  'otPill': string;

  'page': string;

  'spin': string;

  'statusApproved': string;

  'statusDraft': string;

  'statusPill': string;

  'statusRejected': string;

  'statusSubmitted': string;

  'stepBtn': string;

  'taskCard': string;

  'taskStack': string;

  'validList': string;

}

declare const strings: IExportStyles;

export default strings;