// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'actions': string;

  'approved': string;

  'btn': string;

  'btnConfirm': string;

  'btnDefault': string;

  'btnPrimary': string;

  'colDelete': string;

  'colDesc': string;

  'colHours': string;

  'confirmRow': string;

  'confirmText': string;

  'container': string;

  'dateLabel': string;

  'dayNav': string;

  'deleteBtn': string;

  'dismissBtn': string;

  'draft': string;

  'error': string;

  'fadeIn': string;

  'header': string;

  'homeBtn': string;

  'info': string;

  'loadingWrap': string;

  'messageBar': string;

  'navBtn': string;

  'numberInput': string;

  'readOnlyNotice': string;

  'rejected': string;

  'select': string;

  'spin': string;

  'spinner': string;

  'statusBar': string;

  'statusDot': string;

  'submitted': string;

  'success': string;

  'tableCard': string;

  'tableWrap': string;

  'tdCenter': string;

  'textarea': string;

  'timesheetTable': string;

  'title': string;

  'totalExceeds': string;

  'totalLabel': string;

  'totalsRow': string;

  'validationList': string;

  'warning': string;

}

declare const strings: IExportStyles;

export default strings;