// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'approved': string;

  'badge': string;

  'btn': string;

  'btnDefault': string;

  'btnExcel': string;

  'btnPdf': string;

  'colDate': string;

  'colHours': string;

  'colStatus': string;

  'container': string;

  'dismissBtn': string;

  'draft': string;

  'emptyState': string;

  'emptySubtitle': string;

  'emptyTitle': string;

  'error': string;

  'exportBar': string;

  'fadeIn': string;

  'filterCard': string;

  'filterGroup': string;

  'filterGroupFull': string;

  'filterInput': string;

  'filterRow': string;

  'filterSelect': string;

  'filterTitle': string;

  'header': string;

  'homeBtn': string;

  'loadingWrap': string;

  'messageBar': string;

  'optional': string;

  'previewTable': string;

  'rejected': string;

  'resultsSection': string;

  'spin': string;

  'spinner': string;

  'spinnerSm': string;

  'spinnerSmDark': string;

  'submitted': string;

  'success': string;

  'summaryItem': string;

  'summaryLabel': string;

  'summaryStrip': string;

  'summaryValue': string;

  'summaryValueSm': string;

  'tableCard': string;

  'tableFooter': string;

  'tableWrap': string;

  'tdHours': string;

  'tdStatus': string;

  'title': string;

}

declare const strings: IExportStyles;

export default strings;