// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'action-icon': string;

  'animate-fade-in': string;

  'animate-scale-in': string;

  'animate-slide-up': string;

  'badge-text': string;

  'bg-gradient-cool': string;

  'bg-gradient-modern': string;

  'bg-gradient-warm': string;

  'card-gradient-primary': string;

  'card-gradient-purple': string;

  'card-gradient-success': string;

  'card-gradient-warning': string;

  'dashboard-header': string;

  'dashboard-page-title': string;

  'dashboard-root': string;

  'dashboard-section-title': string;

  'fadeIn': string;

  'flex-center': string;

  'flex-col-center': string;

  'header-content': string;

  'hover-glow': string;

  'hover-lift': string;

  'modern-card': string;

  'nav-card': string;

  'nav-card-action': string;

  'nav-card-badge': string;

  'nav-card-content': string;

  'nav-card-description': string;

  'nav-card-glow': string;

  'nav-card-header': string;

  'nav-card-icon': string;

  'nav-card-primary': string;

  'nav-card-title': string;

  'nav-item': string;

  'navigation-grid': string;

  'quick-access-section': string;

  'scaleIn': string;

  'section-header': string;

  'section-subtitle': string;

  'section-title': string;

  'slideUp': string;

  'text-gradient-primary': string;

  'webpart-container': string;

}

declare const strings: IExportStyles;

export default strings;