// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'approved': string;

  'badge': string;

  'btn': string;

  'btnApprove': string;

  'btnDefault': string;

  'btnPrimary': string;

  'btnReject': string;

  'btnResubmit': string;

  'colHrs': string;

  'commentField': string;

  'container': string;

  'dismissBtn': string;

  'dot': string;

  'draft': string;

  'emptyState': string;

  'emptySubtitle': string;

  'emptyTitle': string;

  'error': string;

  'fadeIn': string;

  'filterBar': string;

  'filterGroup': string;

  'filterGroupWide': string;

  'filterInput': string;

  'filterSelect': string;

  'fluentBtnApprove': string;

  'fluentBtnReject': string;

  'fluentBtnResubmit': string;

  'header': string;

  'homeBtn': string;

  'list': string;

  'loadingWrap': string;

  'messageBar': string;

  'modalBody': string;

  'modalCloseBtn': string;

  'modalContainer': string;

  'modalFooter': string;

  'modalHeader': string;

  'modalTitle': string;

  'panelFooter': string;

  'panelMeta': string;

  'panelMetaDetail': string;

  'panelMetaName': string;

  'panelTable': string;

  'panelTableWrap': string;

  'rejected': string;

  'required': string;

  'rowCard': string;

  'rowLeft': string;

  'rowMeta': string;

  'rowName': string;

  'rowRight': string;

  'spin': string;

  'spinner': string;

  'spinnerSm': string;

  'submitted': string;

  'success': string;

  'tdCenter': string;

  'title': string;

}

declare const strings: IExportStyles;

export default strings;