// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'approved': string;

  'badge': string;

  'cardDate': string;

  'cardLeft': string;

  'cardMeta': string;

  'container': string;

  'dot': string;

  'draft': string;

  'emptyIcon': string;

  'emptyState': string;

  'emptySubtitle': string;

  'emptyTitle': string;

  'errorBar': string;

  'fadeIn': string;

  'filterBar': string;

  'filterGroup': string;

  'filterInput': string;

  'filterSelect': string;

  'footer': string;

  'header': string;

  'homeBtn': string;

  'list': string;

  'loadingWrap': string;

  'otBadge': string;

  'rejected': string;

  'spin': string;

  'spinner': string;

  'submitted': string;

  'summaryCard': string;

  'title': string;

}

declare const strings: IExportStyles;

export default strings;