// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'animate-fade-in': string;

  'animate-scale-in': string;

  'animate-slide-up': string;

  'bg-gradient-cool': string;

  'bg-gradient-modern': string;

  'bg-gradient-warm': string;

  'card-gradient-primary': string;

  'card-gradient-purple': string;

  'card-gradient-success': string;

  'card-gradient-warning': string;

  'fadeIn': string;

  'flex-center': string;

  'flex-col-center': string;

  'hover-glow': string;

  'hover-lift': string;

  'modern-card': string;

  'scaleIn': string;

  'slideUp': string;

  'text-gradient-primary': string;

}

declare const strings: IExportStyles;

export default strings;