// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'activityBlue': string;

  'activityContent': string;

  'activityDescription': string;

  'activityGray': string;

  'activityGreen': string;

  'activityIcon': string;

  'activityItem': string;

  'activityList': string;

  'activityRed': string;

  'activityTime': string;

  'activityTitle': string;

  'analyticsContainer': string;

  'analyticsHeader': string;

  'analyticsHeaderLeft': string;

  'analyticsSubtitle': string;

  'analyticsTitle': string;

  'animate-fade-in': string;

  'animate-scale-in': string;

  'animate-slide-up': string;

  'bg-gradient-cool': string;

  'bg-gradient-modern': string;

  'bg-gradient-warm': string;

  'card-gradient-primary': string;

  'card-gradient-purple': string;

  'card-gradient-success': string;

  'card-gradient-warning': string;

  'chart': string;

  'chartContainer': string;

  'chartFullWidth': string;

  'chartMedium': string;

  'chartTitle': string;

  'chartsGrid': string;

  'chartsRow': string;

  'emptyActivity': string;

  'emptyContainer': string;

  'errorContainer': string;

  'fadeIn': string;

  'flex-center': string;

  'flex-col-center': string;

  'hover-glow': string;

  'hover-lift': string;

  'loadingContainer': string;

  'modern-card': string;

  'recentActivity': string;

  'scaleIn': string;

  'slideUp': string;

  'spin': string;

  'spinner': string;

  'statsCard': string;

  'statsCardBlue': string;

  'statsCardGreen': string;

  'statsCardOrange': string;

  'statsCardPurple': string;

  'statsContent': string;

  'statsGrid': string;

  'statsIcon': string;

  'statsSubtitle': string;

  'statsTitle': string;

  'statsTrend': string;

  'statsValue': string;

  'text-gradient-primary': string;

  'toggleBtn': string;

  'toggleBtnActive': string;

  'trendDown': string;

  'trendIcon': string;

  'trendUp': string;

  'viewToggle': string;

}

declare const strings: IExportStyles;

export default strings;