// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'links': string;

  'teams': string;

  'timeSheet': string;

  'welcome': string;

  'welcomeImage': string;

}

declare const strings: IExportStyles;

export default strings;