define([], function () {
  return {
    // SPFx boilerplate
    "PropertyPaneDescription": "TimeSheet WebPart configuration",
    "BasicGroupName": "Settings",
    "DescriptionFieldLabel": "Description",

    // Shared
    "Home": "Home",
    "Loading": "Loading",
    "Save": "Save",
    "Cancel": "Cancel",
    "Confirm": "Confirm",
    "Close": "Close",
    "Edit": "Edit",
    "Add": "Add",
    "Delete": "Delete",
    "Active": "Active",
    "Inactive": "Inactive",
    "Saving": "Saving…",
    "StatusDraft": "Draft",
    "StatusSubmitted": "Submitted",
    "StatusApproved": "Approved",
    "StatusRejected": "Rejected",
    "AllStatuses": "All Statuses",
    "Project": "Project",
    "Category": "Category",
    "Hours": "Hours",
    "Description": "Description",
    "Date": "Date",
    "From": "From",
    "To": "To",
    "Status": "Status",
    "Employee": "Employee",
    "Actions": "Actions",
    "Hrs": "hrs",
    "Total": "Total",

    // HomePage
    "DashboardTitle": "TimeSheet Dashboard",
    "WelcomeMessage": "Welcome, {name} · {role}",
    "QuickAccess": "Quick Access",
    "QuickAccessSubtitle": "Choose an action to get started",
    "NavMyTimesheet": "My Timesheet",
    "NavMyTimesheetSub": "Calendar · Add entries by date",
    "NavMySubmissions": "My Submissions",
    "NavMySubmissionsSub": "Past timesheets",
    "NavTeamTimesheets": "Team Timesheets",
    "NavTeamTimesheetsSub": "Review & approve",
    "NavExportReport": "Export Report",
    "NavExportReportSub": "Excel or PDF",
    "NavManageProjects": "Manage Projects",
    "NavManageProjectsSub": "Projects & categories",

    // CalendarView
    "CalendarTitle": "Timesheet Calendar",
    "MonthNames": ["January","February","March","April","May","June","July","August","September","October","November","December"],
    "DayNamesShort": ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],
    "DayNamesFull": ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],
    "LegendHint": "Click any past date to add or edit entries",
    "NoEntriesHint": "No entries yet. Click a date on the calendar to get started.",
    "EntriesThisPeriod": "Entries This Period",
    "ClickToEdit": "Click to edit entries",
    "ClickToAdd": "Click to add entries",
    "TaskLabel": "Task {n}",
    "SelectProject": "Select project…",
    "SelectCategory": "Select category…",
    "WhatDidYouWorkOn": "What did you work on?",
    "HrsTotal": "hrs total",
    "OverLimit": "⚠ over limit",
    "ConfirmSubmit": "Confirm submit?",
    "YesSubmit": "Yes, Submit",
    "SubmittedAwaiting": "Submitted — awaiting manager review.",
    "ManagerFeedback": "Manager feedback:",
    "RemoveTask": "Remove task",
    "AddAnotherTask": "Add another task",
    "SaveDraft": "Save Draft",
    "Submit": "Submit",
    "SaveDraftSuccess": "Draft saved successfully.",
    "SaveDraftFailed": "Failed to save draft. Please try again.",
    "SubmitSuccess": "Timesheet submitted successfully.",
    "SubmitFailed": "Failed to submit timesheet. Please try again.",
    "LoadFailed": "Failed to load data. Please try again.",

    // DailyTimesheetForm
    "DailyTimesheetTitle": "Daily Timesheet",
    "PreviousDay": "Previous day",
    "NextDay": "Next day",
    "ActivityCategory": "Activity Category",
    "TaskDescription": "Task Description",
    "SelectProjectOpt": "— Select project —",
    "SelectCategoryOpt": "— Select category —",
    "DescribePlaceholder": "Describe the task…",
    "AddTask": "Add Task",
    "Exceeds24h": "Exceeds 24 hr limit",
    "ConfirmSubmitDate": "Submit timesheet for {date}?",
    "SubmittedAwaitingReview": "This timesheet has been submitted and is awaiting review.",
    "RemoveRow": "Remove row",
    "ManagerCommentLabel": "Manager Comments",

    // ManagerDashboard
    "TeamTimesheetsTitle": "Team Timesheets",
    "FilterByEmail": "Filter by email…",
    "NoTimesheetsFound": "No timesheets found",
    "NoTimesheetsHint": "Try adjusting the date range, status, or employee filter.",
    "ApproveBtn": "Approve",
    "RejectBtn": "Reject",
    "RequestResubmitBtn": "Request Re-submit",
    "ApproveModal": "Approve Timesheet",
    "RejectModal": "Reject Timesheet",
    "RequestResubmitModal": "Request Re-submission",
    "ConfirmApprove": "Confirm Approve",
    "SendResubmit": "Send Re-submit Request",
    "ConfirmReject": "Confirm Reject",
    "ManagerCommentPlaceholder": "Provide feedback for the employee…",
    "ApprovedMsg": "Approved timesheet for {name} on {date}.",
    "RejectedMsg": "Successfully rejected timesheet for {name}.",
    "ResubmitMsg": "Successfully requested re-submission for timesheet for {name}.",
    "LoadTeamFailed": "Failed to load team timesheets.",
    "LoadingTeam": "Loading team timesheets…",
    "Processing": "Processing…",
    "Tasks": "task(s)",

    // MyTimesheetHistory
    "HistoryTitle": "My Timesheet History",
    "NoEntriesFound": "No entries found",
    "NoEntriesHintHistory": "Try adjusting the date range or status filter.",
    "LoadHistoryFailed": "Failed to load timesheet history.",
    "LoadingHistory": "Loading history…",
    "Showing": "Showing",
    "Days": "day(s)",

    // AdminPanel
    "AdminTitle": "Manage Projects & Categories",
    "AdminSubtitle": "Configure projects and activity categories",
    "ProjectsTab": "Projects",
    "CategoriesTab": "Activity Categories",
    "AddProject": "Add Project",
    "AddCategory": "Add Category",
    "ProjectName": "Project Name",
    "ProjectCode": "Project Code",
    "ClientName": "Client Name",
    "SortOrder": "Sort Order",
    "ProjectNamePlaceholder": "Enter project name",
    "ProjectCodePlaceholder": "e.g. PROJ-001",
    "ClientNamePlaceholder": "Enter client name",
    "CategoryNamePlaceholder": "Enter category name",
    "OptionalDescription": "Optional description",
    "EditProject": "Edit Project",
    "AddProjectModal": "Add Project",
    "EditCategory": "Edit Category",
    "AddCategoryModal": "Add Category",
    "UpdateProject": "Update Project",
    "UpdateCategory": "Update Category",
    "ProjectRequired": "Project Name and Project Code are required.",
    "CategoryRequired": "Category Name is required.",
    "ProjectUpdated": "Project updated successfully.",
    "ProjectAdded": "Project added successfully.",
    "ProjectSaveFailed": "Failed to save project.",
    "CategoryUpdated": "Category updated.",
    "CategoryAdded": "Category added.",
    "CategorySaveFailed": "Failed to save category.",
    "LoadProjectsFailed": "Failed to load projects.",
    "LoadCategoriesFailed": "Failed to load categories.",
    "LoadingProjects": "Loading projects…",
    "LoadingCategories": "Loading categories…",
    "NoProjects": "No projects found.",
    "NoCategories": "No categories found.",
    "Code": "Code",
    "Activate": "Activate",
    "Deactivate": "Deactivate",
    "BackToHome": "Back to Home",

    // ExportPanel
    "ExportTitle": "Export Timesheet Report",
    "FilterOptions": "Filter Options",
    "EmployeeEmail": "Employee Email",
    "Optional": "(optional)",
    "EmailPlaceholder": "e.g. john@company.com",
    "PreviewData": "Preview Data",
    "ExportExcel": "Export to Excel",
    "ExportPdf": "Export to PDF",
    "Exporting": "Exporting…",
    "LoadingData": "Loading data…",
    "LoadExportFailed": "Failed to load data. Please try again.",
    "ExcelSuccess": "Excel file downloaded successfully.",
    "ExcelFailed": "Excel export failed. Please try again.",
    "PdfSuccess": "PDF file downloaded successfully.",
    "PdfFailed": "PDF export failed. Please try again.",
    "Records": "Records",
    "TotalHours": "Total Hours",
    "Employees": "Employees",
    "Period": "Period",
    "NoDataFound": "No data found",
    "NoDataHint": "Try adjusting your filters and previewing again.",

    // DashboardAnalytics
    "AnalyticsTitle": "Dashboard Analytics",
    "AnalyticsSubtitle": "Your timesheet insights and trends",
    "TotalHoursCard": "Total Hours",
    "ThisMonth": "This month",
    "AvgDaily": "Avg Daily",
    "Last7Days": "Last 7 days",
    "SubmittedCard": "Submitted",
    "ThisWeek": "This week",
    "ApprovedCard": "Approved",
    "Last7DaysChart": "Last 7 Days — Hours Trend",
    "WeekDistribution": "This Week's Distribution",
    "MonthlyByProject": "Monthly Hours by Project",
    "RecentActivity": "Recent Activity",
    "NoRecentActivity": "No recent activity",
    "LoadingAnalytics": "Loading analytics...",
    "AnalyticsFailed": "Failed to load analytics data",
    "NoAnalyticsData": "No analytics data available",

    // Team DashboardAnalytics
    "TeamAnalyticsTitle": "Team Analytics",
    "TeamAnalyticsSubtitle": "All employees · This month",
    "MyAnalyticsToggle": "My Analytics",
    "TeamAnalyticsToggle": "Team Overview",
    "TotalTeamHoursCard": "Total Team Hours",
    "ActiveEmployeesCard": "Active Employees",
    "PendingApprovalsCard": "Pending Approvals",
    "ApprovedThisMonthCard": "Approved This Month",
    "HoursByEmployee": "Hours by Employee",
    "TeamWeekDistribution": "Team Weekly Distribution",
    "TeamLast7DaysChart": "Team Hours — Last 7 Days",

    // App shell
    "LoadingApp": "Loading Timesheet App...",
    "LoadFailedApp": "Unable to load the application. Please refresh the page.",
    "UserProfileFailed": "Failed to load user profile. Defaulting to Employee role.",
    "LoadingEllipsis": "Loading..."
  };
});
