define([], function () {
  return {
    // SPFx boilerplate
    "PropertyPaneDescription": "تكوين الجزء الويب لجدول الوقت",
    "BasicGroupName": "الإعدادات",
    "DescriptionFieldLabel": "الوصف",

    // Shared
    "Home": "الرئيسية",
    "Loading": "جارٍ التحميل",
    "Save": "حفظ",
    "Cancel": "إلغاء",
    "Confirm": "تأكيد",
    "Close": "إغلاق",
    "Edit": "تعديل",
    "Add": "إضافة",
    "Delete": "حذف",
    "Active": "نشط",
    "Inactive": "غير نشط",
    "Saving": "جارٍ الحفظ…",
    "StatusDraft": "مسودة",
    "StatusSubmitted": "مُقدَّم",
    "StatusApproved": "معتمد",
    "StatusRejected": "مرفوض",
    "AllStatuses": "جميع الحالات",
    "Project": "المشروع",
    "Category": "الفئة",
    "Hours": "الساعات",
    "Description": "الوصف",
    "Date": "التاريخ",
    "From": "من",
    "To": "إلى",
    "Status": "الحالة",
    "Employee": "الموظف",
    "Actions": "الإجراءات",
    "Hrs": "س",
    "Total": "الإجمالي",

    // HomePage
    "DashboardTitle": "لوحة تحكم جدول الوقت",
    "WelcomeMessage": "مرحباً، {name} · {role}",
    "QuickAccess": "الوصول السريع",
    "QuickAccessSubtitle": "اختر إجراءً للبدء",
    "NavMyTimesheet": "جدول وقتي",
    "NavMyTimesheetSub": "التقويم · إضافة إدخالات حسب التاريخ",
    "NavMySubmissions": "تقديماتي",
    "NavMySubmissionsSub": "جداول الوقت السابقة",
    "NavTeamTimesheets": "جداول وقت الفريق",
    "NavTeamTimesheetsSub": "مراجعة والموافقة",
    "NavExportReport": "تصدير التقرير",
    "NavExportReportSub": "Excel أو PDF",
    "NavManageProjects": "إدارة المشاريع",
    "NavManageProjectsSub": "المشاريع والفئات",

    // CalendarView
    "CalendarTitle": "تقويم جداول الوقت",
    "MonthNames": ["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],
    "DayNamesShort": ["أحد","اثن","ثلا","أرب","خمس","جمع","سبت"],
    "DayNamesFull": ["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"],
    "LegendHint": "انقر على أي تاريخ ماضٍ لإضافة إدخالات أو تعديلها",
    "NoEntriesHint": "لا توجد إدخالات حتى الآن. انقر على تاريخ في التقويم للبدء.",
    "EntriesThisPeriod": "إدخالات هذه الفترة",
    "ClickToEdit": "انقر لتعديل الإدخالات",
    "ClickToAdd": "انقر لإضافة إدخالات",
    "TaskLabel": "المهمة {n}",
    "SelectProject": "اختر مشروعاً…",
    "SelectCategory": "اختر فئةً…",
    "WhatDidYouWorkOn": "ماذا عملت؟",
    "HrsTotal": "ساعات الإجمالي",
    "OverLimit": "⚠ تجاوز الحد",
    "ConfirmSubmit": "تأكيد التقديم؟",
    "YesSubmit": "نعم، قدِّم",
    "SubmittedAwaiting": "مُقدَّم — في انتظار مراجعة المدير.",
    "ManagerFeedback": "ملاحظات المدير:",
    "RemoveTask": "إزالة المهمة",
    "AddAnotherTask": "إضافة مهمة أخرى",
    "SaveDraft": "حفظ المسودة",
    "Submit": "تقديم",
    "SaveDraftSuccess": "تم حفظ المسودة بنجاح.",
    "SaveDraftFailed": "فشل حفظ المسودة. يرجى المحاولة مرة أخرى.",
    "SubmitSuccess": "تم تقديم جدول الوقت بنجاح.",
    "SubmitFailed": "فشل تقديم جدول الوقت. يرجى المحاولة مرة أخرى.",
    "LoadFailed": "فشل تحميل البيانات. يرجى المحاولة مرة أخرى.",

    // DailyTimesheetForm
    "DailyTimesheetTitle": "جدول الوقت اليومي",
    "PreviousDay": "اليوم السابق",
    "NextDay": "اليوم التالي",
    "ActivityCategory": "فئة النشاط",
    "TaskDescription": "وصف المهمة",
    "SelectProjectOpt": "— اختر مشروعاً —",
    "SelectCategoryOpt": "— اختر فئةً —",
    "DescribePlaceholder": "صف المهمة…",
    "AddTask": "إضافة مهمة",
    "Exceeds24h": "يتجاوز حد 24 ساعة",
    "ConfirmSubmitDate": "تقديم جدول الوقت لتاريخ {date}؟",
    "SubmittedAwaitingReview": "تم تقديم جدول الوقت هذا وهو في انتظار المراجعة.",
    "RemoveRow": "إزالة الصف",
    "ManagerCommentLabel": "تعليقات المدير",

    // ManagerDashboard
    "TeamTimesheetsTitle": "جداول وقت الفريق",
    "FilterByEmail": "تصفية بالبريد الإلكتروني…",
    "NoTimesheetsFound": "لم يتم العثور على جداول وقت",
    "NoTimesheetsHint": "حاول ضبط نطاق التاريخ أو الحالة أو تصفية الموظف.",
    "ApproveBtn": "موافقة",
    "RejectBtn": "رفض",
    "RequestResubmitBtn": "طلب إعادة التقديم",
    "ApproveModal": "الموافقة على جدول الوقت",
    "RejectModal": "رفض جدول الوقت",
    "RequestResubmitModal": "طلب إعادة التقديم",
    "ConfirmApprove": "تأكيد الموافقة",
    "SendResubmit": "إرسال طلب إعادة التقديم",
    "ConfirmReject": "تأكيد الرفض",
    "ManagerCommentPlaceholder": "قدِّم ملاحظات للموظف…",
    "ApprovedMsg": "تمت الموافقة على جدول وقت {name} بتاريخ {date}.",
    "RejectedMsg": "تم رفض جدول وقت {name} بنجاح.",
    "ResubmitMsg": "تم طلب إعادة تقديم جدول وقت {name} بنجاح.",
    "LoadTeamFailed": "فشل تحميل جداول وقت الفريق.",
    "LoadingTeam": "جارٍ تحميل جداول وقت الفريق…",
    "Processing": "جارٍ المعالجة…",
    "Tasks": "مهمة/مهام",

    // MyTimesheetHistory
    "HistoryTitle": "سجل جداول وقتي",
    "NoEntriesFound": "لم يتم العثور على إدخالات",
    "NoEntriesHintHistory": "حاول ضبط نطاق التاريخ أو تصفية الحالة.",
    "LoadHistoryFailed": "فشل تحميل السجل.",
    "LoadingHistory": "جارٍ تحميل السجل…",
    "Showing": "عرض",
    "Days": "يوم/أيام",

    // AdminPanel
    "AdminTitle": "إدارة المشاريع والفئات",
    "AdminSubtitle": "تكوين المشاريع وفئات النشاط",
    "ProjectsTab": "المشاريع",
    "CategoriesTab": "فئات النشاط",
    "AddProject": "إضافة مشروع",
    "AddCategory": "إضافة فئة",
    "ProjectName": "اسم المشروع",
    "ProjectCode": "رمز المشروع",
    "ClientName": "اسم العميل",
    "SortOrder": "ترتيب الفرز",
    "ProjectNamePlaceholder": "أدخل اسم المشروع",
    "ProjectCodePlaceholder": "مثال: PROJ-001",
    "ClientNamePlaceholder": "أدخل اسم العميل",
    "CategoryNamePlaceholder": "أدخل اسم الفئة",
    "OptionalDescription": "وصف اختياري",
    "EditProject": "تعديل المشروع",
    "AddProjectModal": "إضافة مشروع",
    "EditCategory": "تعديل الفئة",
    "AddCategoryModal": "إضافة فئة",
    "UpdateProject": "تحديث المشروع",
    "UpdateCategory": "تحديث الفئة",
    "ProjectRequired": "اسم المشروع ورمزه مطلوبان.",
    "CategoryRequired": "اسم الفئة مطلوب.",
    "ProjectUpdated": "تم تحديث المشروع بنجاح.",
    "ProjectAdded": "تمت إضافة المشروع بنجاح.",
    "ProjectSaveFailed": "فشل حفظ المشروع.",
    "CategoryUpdated": "تم تحديث الفئة.",
    "CategoryAdded": "تمت إضافة الفئة.",
    "CategorySaveFailed": "فشل حفظ الفئة.",
    "LoadProjectsFailed": "فشل تحميل المشاريع.",
    "LoadCategoriesFailed": "فشل تحميل الفئات.",
    "LoadingProjects": "جارٍ تحميل المشاريع…",
    "LoadingCategories": "جارٍ تحميل الفئات…",
    "NoProjects": "لم يتم العثور على مشاريع.",
    "NoCategories": "لم يتم العثور على فئات.",
    "Code": "الرمز",
    "Activate": "تفعيل",
    "Deactivate": "تعطيل",
    "BackToHome": "العودة إلى الرئيسية",

    // ExportPanel
    "ExportTitle": "تصدير تقرير جدول الوقت",
    "FilterOptions": "خيارات التصفية",
    "EmployeeEmail": "البريد الإلكتروني للموظف",
    "Optional": "(اختياري)",
    "EmailPlaceholder": "مثال: ali@company.com",
    "PreviewData": "معاينة البيانات",
    "ExportExcel": "تصدير إلى Excel",
    "ExportPdf": "تصدير إلى PDF",
    "Exporting": "جارٍ التصدير…",
    "LoadingData": "جارٍ تحميل البيانات…",
    "LoadExportFailed": "فشل تحميل البيانات. يرجى المحاولة مرة أخرى.",
    "ExcelSuccess": "تم تنزيل ملف Excel بنجاح.",
    "ExcelFailed": "فشل تصدير Excel. يرجى المحاولة مرة أخرى.",
    "PdfSuccess": "تم تنزيل ملف PDF بنجاح.",
    "PdfFailed": "فشل تصدير PDF. يرجى المحاولة مرة أخرى.",
    "Records": "السجلات",
    "TotalHours": "إجمالي الساعات",
    "Employees": "الموظفون",
    "Period": "الفترة",
    "NoDataFound": "لم يتم العثور على بيانات",
    "NoDataHint": "حاول ضبط عوامل التصفية والمعاينة مرة أخرى.",

    // DashboardAnalytics
    "AnalyticsTitle": "تحليلات لوحة التحكم",
    "AnalyticsSubtitle": "رؤى واتجاهات جدول الوقت الخاص بك",
    "TotalHoursCard": "إجمالي الساعات",
    "ThisMonth": "هذا الشهر",
    "AvgDaily": "المتوسط اليومي",
    "Last7Days": "آخر 7 أيام",
    "SubmittedCard": "مُقدَّم",
    "ThisWeek": "هذا الأسبوع",
    "ApprovedCard": "معتمد",
    "Last7DaysChart": "آخر 7 أيام — اتجاه الساعات",
    "WeekDistribution": "توزيع الأسبوع الحالي",
    "MonthlyByProject": "الساعات الشهرية حسب المشروع",
    "RecentActivity": "النشاط الأخير",
    "NoRecentActivity": "لا يوجد نشاط أخير",
    "LoadingAnalytics": "جارٍ تحميل التحليلات...",
    "AnalyticsFailed": "فشل تحميل بيانات التحليلات",
    "NoAnalyticsData": "لا تتوفر بيانات تحليلات",

    // App shell
    "LoadingApp": "جارٍ تحميل تطبيق جدول الوقت...",
    "LoadFailedApp": "تعذّر تحميل التطبيق. يرجى تحديث الصفحة.",
    "UserProfileFailed": "فشل تحميل ملف تعريف المستخدم. سيتم استخدام دور الموظف الافتراضي.",
    "LoadingEllipsis": "جارٍ التحميل..."
  };
});
