define([], function () {
  return {
    // SPFx boilerplate
    "PropertyPaneDescription": "Configuration du composant WebPart Feuille de temps",
    "BasicGroupName": "Paramètres",
    "DescriptionFieldLabel": "Description",

    // Shared
    "Home": "Maison",
    "Loading": "Chargement",
    "Save": "Enregistrer",
    "Cancel": "Annuler",
    "Confirm": "Confirmer",
    "Close": "Fermer",
    "Edit": "Modifier",
    "Add": "Ajouter",
    "Delete": "Supprimer",
    "Active": "Actif",
    "Inactive": "Inactif",
    "Saving": "Enregistrement…",
    "StatusDraft": "Brouillon",
    "StatusSubmitted": "Soumis",
    "StatusApproved": "Approuvé",
    "StatusRejected": "Rejeté",
    "AllStatuses": "Tous les statuts",
    "Project": "Projet",
    "Category": "Catégorie",
    "Hours": "Heures",
    "Description": "Description",
    "Date": "Date",
    "From": "Du",
    "To": "Au",
    "Status": "Statut",
    "Employee": "Employé",
    "Actions": "Actions",
    "Hrs": "h",
    "Total": "Total",

    // HomePage
    "DashboardTitle": "Tableau de bord Feuille de temps",
    "WelcomeMessage": "Bienvenue, {name} · {role}",
    "QuickAccess": "Accès rapide",
    "QuickAccessSubtitle": "Choisissez une action pour commencer",
    "NavMyTimesheet": "Ma feuille de temps",
    "NavMyTimesheetSub": "Calendrier · Ajouter des entrées par date",
    "NavMySubmissions": "Mes soumissions",
    "NavMySubmissionsSub": "Feuilles de temps passées",
    "NavTeamTimesheets": "Feuilles de temps de l'équipe",
    "NavTeamTimesheetsSub": "Examiner et approuver",
    "NavExportReport": "Exporter le rapport",
    "NavExportReportSub": "Excel ou PDF",
    "NavManageProjects": "Gérer les projets",
    "NavManageProjectsSub": "Projets et catégories",

    // CalendarView
    "CalendarTitle": "Calendrier des feuilles de temps",
    "MonthNames": ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"],
    "DayNamesShort": ["Dim","Lun","Mar","Mer","Jeu","Ven","Sam"],
    "DayNamesFull": ["Dimanche","Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"],
    "LegendHint": "Cliquez sur n'importe quelle date passée pour ajouter ou modifier des entrées",
    "NoEntriesHint": "Aucune entrée pour le moment. Cliquez sur une date du calendrier pour commencer.",
    "EntriesThisPeriod": "Entrées de cette période",
    "ClickToEdit": "Cliquer pour modifier les entrées",
    "ClickToAdd": "Cliquer pour ajouter des entrées",
    "TaskLabel": "Tâche {n}",
    "SelectProject": "Sélectionner un projet…",
    "SelectCategory": "Sélectionner une catégorie…",
    "WhatDidYouWorkOn": "Sur quoi avez-vous travaillé ?",
    "HrsTotal": "h au total",
    "OverLimit": "⚠ limite dépassée",
    "ConfirmSubmit": "Confirmer la soumission ?",
    "YesSubmit": "Oui, soumettre",
    "SubmittedAwaiting": "Soumis — en attente de l'approbation du responsable.",
    "ManagerFeedback": "Commentaire du responsable :",
    "RemoveTask": "Supprimer la tâche",
    "AddAnotherTask": "Ajouter une autre tâche",
    "SaveDraft": "Enregistrer le brouillon",
    "Submit": "Soumettre",
    "SaveDraftSuccess": "Brouillon enregistré avec succès.",
    "SaveDraftFailed": "Échec de l'enregistrement du brouillon. Veuillez réessayer.",
    "SubmitSuccess": "Feuille de temps soumise avec succès.",
    "SubmitFailed": "Échec de la soumission de la feuille de temps. Veuillez réessayer.",
    "LoadFailed": "Échec du chargement des données. Veuillez réessayer.",

    // DailyTimesheetForm
    "DailyTimesheetTitle": "Feuille de temps quotidienne",
    "PreviousDay": "Jour précédent",
    "NextDay": "Jour suivant",
    "ActivityCategory": "Catégorie d'activité",
    "TaskDescription": "Description de la tâche",
    "SelectProjectOpt": "— Sélectionner un projet —",
    "SelectCategoryOpt": "— Sélectionner une catégorie —",
    "DescribePlaceholder": "Décrivez la tâche…",
    "AddTask": "Ajouter une tâche",
    "Exceeds24h": "Dépasse la limite de 24 h",
    "ConfirmSubmitDate": "Soumettre la feuille de temps pour le {date} ?",
    "SubmittedAwaitingReview": "Cette feuille de temps a été soumise et est en attente d'examen.",
    "RemoveRow": "Supprimer la ligne",
    "ManagerCommentLabel": "Commentaires du responsable",

    // ManagerDashboard
    "TeamTimesheetsTitle": "Feuilles de temps de l'équipe",
    "FilterByEmail": "Filtrer par e-mail…",
    "NoTimesheetsFound": "Aucune feuille de temps trouvée",
    "NoTimesheetsHint": "Essayez d'ajuster la plage de dates, le statut ou le filtre employé.",
    "ApproveBtn": "Approuver",
    "RejectBtn": "Rejeter",
    "RequestResubmitBtn": "Demander une re-soumission",
    "ApproveModal": "Approuver la feuille de temps",
    "RejectModal": "Rejeter la feuille de temps",
    "RequestResubmitModal": "Demander une re-soumission",
    "ConfirmApprove": "Confirmer l'approbation",
    "SendResubmit": "Envoyer la demande de re-soumission",
    "ConfirmReject": "Confirmer le rejet",
    "ManagerCommentPlaceholder": "Fournissez des commentaires à l'employé…",
    "ApprovedMsg": "Feuille de temps approuvée pour {name} le {date}.",
    "RejectedMsg": "Feuille de temps rejetée pour {name}.",
    "ResubmitMsg": "Re-soumission demandée pour la feuille de temps de {name}.",
    "LoadTeamFailed": "Échec du chargement des feuilles de temps de l'équipe.",
    "LoadingTeam": "Chargement des feuilles de temps de l'équipe…",
    "Processing": "Traitement…",
    "Tasks": "tâche(s)",

    // MyTimesheetHistory
    "HistoryTitle": "Historique de mes feuilles de temps",
    "NoEntriesFound": "Aucune entrée trouvée",
    "NoEntriesHintHistory": "Essayez d'ajuster la plage de dates ou le filtre de statut.",
    "LoadHistoryFailed": "Échec du chargement de l'historique.",
    "LoadingHistory": "Chargement de l'historique…",
    "Showing": "Affichage",
    "Days": "jour(s)",

    // AdminPanel
    "AdminTitle": "Gérer les projets et catégories",
    "AdminSubtitle": "Configurer les projets et les catégories d'activité",
    "ProjectsTab": "Projets",
    "CategoriesTab": "Catégories d'activité",
    "AddProject": "Ajouter un projet",
    "AddCategory": "Ajouter une catégorie",
    "ProjectName": "Nom du projet",
    "ProjectCode": "Code du projet",
    "ClientName": "Nom du client",
    "SortOrder": "Ordre de tri",
    "ProjectNamePlaceholder": "Entrez le nom du projet",
    "ProjectCodePlaceholder": "ex. PROJ-001",
    "ClientNamePlaceholder": "Entrez le nom du client",
    "CategoryNamePlaceholder": "Entrez le nom de la catégorie",
    "OptionalDescription": "Description optionnelle",
    "EditProject": "Modifier le projet",
    "AddProjectModal": "Ajouter un projet",
    "EditCategory": "Modifier la catégorie",
    "AddCategoryModal": "Ajouter une catégorie",
    "UpdateProject": "Mettre à jour le projet",
    "UpdateCategory": "Mettre à jour la catégorie",
    "ProjectRequired": "Le nom et le code du projet sont obligatoires.",
    "CategoryRequired": "Le nom de la catégorie est obligatoire.",
    "ProjectUpdated": "Projet mis à jour avec succès.",
    "ProjectAdded": "Projet ajouté avec succès.",
    "ProjectSaveFailed": "Échec de l'enregistrement du projet.",
    "CategoryUpdated": "Catégorie mise à jour.",
    "CategoryAdded": "Catégorie ajoutée.",
    "CategorySaveFailed": "Échec de l'enregistrement de la catégorie.",
    "LoadProjectsFailed": "Échec du chargement des projets.",
    "LoadCategoriesFailed": "Échec du chargement des catégories.",
    "LoadingProjects": "Chargement des projets…",
    "LoadingCategories": "Chargement des catégories…",
    "NoProjects": "Aucun projet trouvé.",
    "NoCategories": "Aucune catégorie trouvée.",
    "Code": "Code",
    "Activate": "Activer",
    "Deactivate": "Désactiver",
    "BackToHome": "Retour à l'accueil",

    // ExportPanel
    "ExportTitle": "Exporter le rapport de feuille de temps",
    "FilterOptions": "Options de filtre",
    "EmployeeEmail": "E-mail de l'employé",
    "Optional": "(optionnel)",
    "EmailPlaceholder": "ex. jean@entreprise.com",
    "PreviewData": "Prévisualiser les données",
    "ExportExcel": "Exporter vers Excel",
    "ExportPdf": "Exporter vers PDF",
    "Exporting": "Exportation…",
    "LoadingData": "Chargement des données…",
    "LoadExportFailed": "Échec du chargement des données. Veuillez réessayer.",
    "ExcelSuccess": "Fichier Excel téléchargé avec succès.",
    "ExcelFailed": "Échec de l'exportation Excel. Veuillez réessayer.",
    "PdfSuccess": "Fichier PDF téléchargé avec succès.",
    "PdfFailed": "Échec de l'exportation PDF. Veuillez réessayer.",
    "Records": "Enregistrements",
    "TotalHours": "Heures totales",
    "Employees": "Employés",
    "Period": "Période",
    "NoDataFound": "Aucune donnée trouvée",
    "NoDataHint": "Essayez d'ajuster vos filtres et prévisualisez à nouveau.",

    // DashboardAnalytics
    "AnalyticsTitle": "Analytique du tableau de bord",
    "AnalyticsSubtitle": "Vos tendances et aperçus de feuille de temps",
    "TotalHoursCard": "Heures totales",
    "ThisMonth": "Ce mois",
    "AvgDaily": "Moy. quotidienne",
    "Last7Days": "7 derniers jours",
    "SubmittedCard": "Soumis",
    "ThisWeek": "Cette semaine",
    "ApprovedCard": "Approuvé",
    "Last7DaysChart": "7 derniers jours — Tendance des heures",
    "WeekDistribution": "Distribution de la semaine",
    "MonthlyByProject": "Heures mensuelles par projet",
    "RecentActivity": "Activité récente",
    "NoRecentActivity": "Aucune activité récente",
    "LoadingAnalytics": "Chargement des analytiques...",
    "AnalyticsFailed": "Échec du chargement des données analytiques",
    "NoAnalyticsData": "Aucune donnée analytique disponible",

    // App shell
    "LoadingApp": "Chargement de l'application Feuille de temps...",
    "LoadFailedApp": "Impossible de charger l'application. Veuillez actualiser la page.",
    "UserProfileFailed": "Échec du chargement du profil utilisateur. Rôle Employé par défaut.",
    "LoadingEllipsis": "Chargement..."
  };
});
